# Training params
epoch : 20

# Classifier
model :
  architecture : torchvision.models.resnet18
  pretrained : True

# Optimizer
optimizer :
  name : torch.optim.Adam
  lr : 0.001

# Criterion
loss_function :
  name : torch.nn.CrossEntropyLoss

# Scheduler
scheduler :
  name : torch.optim.lr_scheduler.StepLR
  gamma : 0.1
  step_size : 7

# Dataset
dataset :
  path : "./Rice_Image_Dataset"
  train_path : "./Rice_Image_Dataset/train"
  test_path : "./Rice_Image_Dataset/test"
  train_split : 0.8
  batch_size : 64
  shuffle : True